const baseUrl = "https://image.tmdb.org/t/p/original";
const trending = [
  {
    adult: false,
    backdrop_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1657955842/Backdrops/JurrasicPark_hxolsm.jpg",
    genre_ids: (3)[(12, 28, 878)],
    id: 507086,
    media_type: "movie",
    original_language: "en",
    original_title: "Jurassic World Dominion",
    overview:
      "Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with historys most fearsome creatures.",
    popularity: 3190.202,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069963/Poster/trending1_zrea2f.jpg",
    release_date: "2022-06-01",
    title: "Jurassic World Dominion",
    video: false,
    vote_average: 6.684,
    vote_count: 1237,
  },
  {
    adult: false,
    backdrop_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1657955843/Backdrops/Thor_r038gf.jpg",
    genre_ids: (3)[(28, 12, 14)],
    id: 616037,
    media_type: "movie",
    original_language: "en",
    original_title: "Thor: Love and Thunder",
    overview:
      "After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now inexplicably wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher's vengeance and stop him before it's too late.",
    popularity: 3675.753,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069961/Poster/trending2_tny8rl.jpg",
    release_date: "2022-07-06",
    title: "Thor: Love and Thunder",
    video: false,
    vote_average: 6.88,
    vote_count: 818,
  },
  {
    adult: false,
    backdrop_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1657955848/Backdrops/DrStrange_fr7kzk.jpg",
    genre_ids: (3)[(14, 28, 12)],
    id: 453395,
    media_type: "movie",
    original_language: "en",
    original_title: "Doctor Strange in the Multiverse of Madness",
    overview:
      "Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.",
    popularity: 4480.794,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069961/Poster/trending3_wxnbcl.jpg",
    release_date: "2022-05-04",
    title: "Doctor Strange in the Multiverse of Madness",
    video: false,
    vote_average: 7.522,
    vote_count: 4396,
  },
  {
    adult: false,
    backdrop_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1657955840/Backdrops/StrangerThings_knmwza.jpg",
    first_air_date: "2016-07-15",
    genre_ids: (3)[(18, 10765, 9648)],
    id: 66732,
    media_type: "tv",
    name: "Stranger Things",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Stranger Things",
    overview:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    popularity: 3200.218,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069961/Poster/trending4_uia3cd.jpg",
    vote_average: 8.631,
    vote_count: 12090,
  },
  {
    adult: false,
    backdrop_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1657955842/Backdrops/SeaBeast_u6mwop.jpg",
    genre_ids: (4)[(16, 12, 10751, 14)],
    id: 560057,
    media_type: "movie",
    original_language: "en",
    original_title: "The Sea Beast",
    overview:
      "The life of a legendary sea monster hunter is turned upside down when a young girl stows away on his ship.",
    popularity: 372.616,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069961/Poster/trending5_gj57lp.jpg",
    release_date: "2022-06-24",
    title: "The Sea Beast",
    video: false,
    vote_average: 7.61,
    vote_count: 187,
  },
  {
    adult: false,
    backdrop_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1657955840/Backdrops/Boys_jekp7d.jpg",
    first_air_date: "2019-07-25",
    genre_ids: (2)[(10765, 10759)],
    id: 76479,
    media_type: "tv",
    name: "The Boys",
    origin_country: ["US"],
    original_language: "en",
    original_name: "The Boys",
    overview:
      "A group of vigilantes known informally as “The Boys” set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.",
    popularity: 2439.426,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069960/Poster/trending6_iw8nav.jpg",
    vote_average: 8.46,
    vote_count: 6653,
  },
  {
    adult: false,
    backdrop_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1657955849/Backdrops/BlackPhone_sdbg9l.jpg",
    genre_ids: (2)[(27, 53)],
    id: 756999,
    media_type: "movie",
    original_language: "en",
    original_title: "The Black Phone",
    overview:
      "Finney Shaw, a shy but clever 13-year-old boy, is abducted by a sadistic killer and trapped in a soundproof basement where screaming is of little use. When a disconnected phone on the wall begins to ring, Finney discovers that he can hear the voices of the killer's previous victims. And they are dead set on making sure that what happened to them doesn't happen to Finney.",
    popularity: 1522.809,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069960/Poster/trending7_ww9wgz.jpg",
    release_date: "2022-06-22",
    title: "The Black Phone",
    video: false,
    vote_average: 7.477,
    vote_count: 395,
  },
  {
    adult: false,
    backdrop_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1657955840/Backdrops/MsMarvel_azltki.jpg",
    first_air_date: "2022-06-08",
    genre_ids: (3)[(10765, 10759, 35)],
    id: 92782,
    media_type: "tv",
    name: "Ms. Marvel",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Ms. Marvel",
    overview:
      "A great student, avid gamer, and voracious fan-fic scribe, Kamala Khan has a special affinity for superheroes, particularly Captain Marvel. However, she struggles to fit in at home and at school — that is, until she gets superpowers like the heroes she's always looked up to. Life is easier with superpowers, right?",
    popularity: 3045.059,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069960/Poster/trending8_b6gkog.jpg",
    vote_average: 7.323,
    vote_count: 330,
  },
  {
    adult: false,
    backdrop_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1657955847/Backdrops/Minion_vz8sje.jpg",
    genre_ids: (5)[(10751, 16, 12, 35, 14)],
    id: 438148,
    media_type: "movie",
    original_language: "en",
    original_title: "Minions: The Rise of Gru",
    overview:
      "A fanboy of a supervillain supergroup known as the Vicious 6, Gru hatches a plan to become evil enough to join them, with the backup of his followers, the Minions.",
    popularity: 11737.572,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069960/Poster/trending9_mu7nro.jpg",
    release_date: "2022-06-29",
    title: "Minions: The Rise of Gru",
    video: false,
    vote_average: 7.676,
    vote_count: 323,
  },
];

const originals = [
  {
    backdrop_path: "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    first_air_date: "2016-07-15",
    genre_ids: (3)[(18, 10765, 9648)],
    id: 66732,
    name: "Stranger Things",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Stranger Things",
    overview:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
    popularity: 3200.218,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069961/Poster/trending4_uia3cd.jpg",
    vote_average: 8.6,
    vote_count: 12060,
  },
  {
    backdrop_path: "/gFFedWBZ7s5sPiR9A1IpileWuFf.jpg",
    first_air_date: "2020-05-22",
    genre_ids: [18],
    id: 102903,
    name: "Control Z",
    origin_country: ["MX"],
    original_language: "es",
    original_name: "Control Z",
    overview:
      "When a hacker begins releasing students' secrets to the entire high school, the socially isolated but observant Sofía works to uncover his/her identity.",
    popularity: 918.408,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069960/Poster/original2_amegky.jpg",
    vote_average: 8.3,
    vote_count: 2124,
  },
  {
    backdrop_path: "/lcTuggU70y6pt6x13Rv1Ffjs93K.jpg",
    first_air_date: "2022-06-24",
    genre_ids: (4)[(10759, 80, 18, 9648)],
    id: 112836,
    name: "Money Heist: Korea - Joint Economic Area",
    origin_country: ["KR"],
    original_language: "ko",
    original_name: "종이의 집: 공동경제구역",
    overview:
      "Disguised under the shadows of a mask, a crew of desperados band together under the leadership of a criminal mastermind known only as “The Professor” to pull off the biggest heist Korea has ever seen.",
    popularity: 882.705,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069959/Poster/original3_zng69c.jpg",
    vote_average: 7.9,
    vote_count: 183,
  },
  {
    backdrop_path: "/ktDJ21QQscbMNQfPpZBsNORxdDx.jpg",
    first_air_date: "2016-01-25",
    genre_ids: (2)[(80, 10765)],
    id: 63174,
    name: "Lucifer",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Lucifer",
    overview:
      "Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.",
    popularity: 838.81,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069960/Poster/original4_kftk6x.jpg",
    vote_average: 8.5,
    vote_count: 12081,
  },
  {
    backdrop_path: "/ciToI1GfkWmzavJIPXh9Xe0Neon.jpg",
    first_air_date: "2019-02-15",
    genre_ids: (3)[(10759, 10765, 18)],
    id: 75006,
    name: "The Umbrella Academy",
    origin_country: ["US"],
    original_language: "en",
    original_name: "The Umbrella Academy",
    overview:
      "A dysfunctional family of superheroes comes together to solve the mystery of their father's death, the threat of the apocalypse and more.",
    popularity: 588.381,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069959/Poster/original5_vfaxuc.jpg",
    vote_average: 8.7,
    vote_count: 8102,
  },
  {
    backdrop_path: "/8Xs20y8gFR0W9u8Yy9NKdpZtSu7.jpg",
    first_air_date: "2022-01-28",
    genre_ids: (3)[(10759, 18, 10765)],
    id: 99966,
    name: "All of Us Are Dead",
    origin_country: ["KR"],
    original_language: "ko",
    original_name: "지금 우리 학교는",
    overview:
      "A high school becomes ground zero for a zombie virus outbreak. Trapped students must fight their way out — or turn into one of the rabid infected.",
    popularity: 506.161,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069959/Poster/original6_wfrnyh.jpg",
    vote_average: 8.5,
    vote_count: 2375,
  },
  {
    backdrop_path: "/voeQ3GolYnXSs9HH0MbMHazNiWm.jpg",
    first_air_date: "2022-07-08",
    genre_ids: [80],
    id: 201331,
    name: "The Longest Night",
    origin_country: ["ES"],
    original_language: "es",
    original_name: "La noche más larga",
    overview:
      "Armed forces surround a psychiatric prison in order to abduct an incarcerated serial killer — but aren't prepared for the battle that ensues.",
    popularity: 420.886,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069959/Poster/original7_lwighe.jpg",
    vote_average: 6.6,
    vote_count: 13,
  },
  {
    backdrop_path: "/qw3J9cNeLioOLoR68WX7z79aCdK.jpg",
    first_air_date: "2021-09-17",
    genre_ids: (3)[(10759, 9648, 18)],
    id: 93405,
    name: "Squid Game",
    origin_country: ["KR"],
    original_language: "ko",
    original_name: "오징어 게임",
    overview:
      "Hundreds of cash-strapped players accept a strange invitation to compete in children's games—with high stakes. But, a tempting prize awaits the victor.",
    popularity: 394.426,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069958/Poster/original8_rrrr9t.jpg",
    vote_average: 7.8,
    vote_count: 10996,
  },
  {
    backdrop_path: "/ggkYRGptz8eKTYnDefEjsX7fazd.jpg",
    first_air_date: "2022-05-26",
    genre_ids: (2)[(16, 10762)],
    id: 158691,
    name: "My Little Pony: Make Your Mark",
    origin_country: ["US"],
    original_language: "en",
    original_name: "My Little Pony: Make Your Mark",
    overview:
      "The series will center on the adventures of Sunny Starscout and her friends after the events depicted in the film.",
    popularity: 392.133,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069958/Poster/original9_bhdnnx.jpg",
    vote_average: 8.2,
    vote_count: 55,
  },
];

const topRated = [
  {
    adult: false,
    backdrop_path: "/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    genre_ids: (2)[(18, 80)],
    id: 278,
    original_language: "en",
    original_title: "The Shawshank Redemption",
    overview:
      "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
    popularity: 72.188,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069958/Poster/top1_prbr0c.jpg",
    release_date: "1994-09-23",
    title: "The Shawshank Redemption",
    video: false,
    vote_average: 8.7,
    vote_count: 21781,
  },
  {
    adult: false,
    backdrop_path: "/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg",
    genre_ids: (3)[(35, 18, 10749)],
    id: 19404,
    original_language: "hi",
    original_title: "दिलवाले दुल्हनिया ले जायेंगे",
    overview:
      "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
    popularity: 29.833,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069958/Poster/top2_wrewfx.jpg",
    release_date: "1995-10-19",
    title: "Dilwale Dulhania Le Jayenge",
    video: false,
    vote_average: 8.7,
    vote_count: 3712,
  },
  {
    adult: false,
    backdrop_path: "/rSPw7tgCH9c6NqICZef4kZjFOQ5.jpg",
    genre_ids: (2)[(18, 80)],
    id: 238,
    original_language: "en",
    original_title: "The Godfather",
    overview:
      "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    popularity: 81.753,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069957/Poster/top3_f3w25i.jpg",
    release_date: "1972-03-14",
    title: "The Godfather",
    video: false,
    vote_average: 8.7,
    vote_count: 16211,
  },
  {
    adult: false,
    backdrop_path: "/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg",
    genre_ids: (3)[(18, 36, 10752)],
    id: 424,
    original_language: "en",
    original_title: "Schindler's List",
    overview:
      "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
    popularity: 43.494,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069957/Poster/top4_dxek4h.jpg",
    release_date: "1993-11-30",
    title: "Schindler's List",
    video: false,
    vote_average: 8.6,
    vote_count: 12927,
  },
  {
    adult: false,
    backdrop_path: "/poec6RqOKY9iSiIUmfyfPfiLtvB.jpg",
    genre_ids: (2)[(18, 80)],
    id: 240,
    original_language: "en",
    original_title: "The Godfather: Part II",
    overview:
      "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
    popularity: 58.451,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069957/Poster/top5_wqp5sn.jpg",
    release_date: "1974-12-20",
    title: "The Godfather: Part II",
    video: false,
    vote_average: 8.6,
    vote_count: 9773,
  },
  {
    adult: false,
    backdrop_path: "/bxSBOAD8AuMHYMdW3jso9npAkgt.jpg",
    genre_ids: (2)[(10751, 18)],
    id: 667257,
    original_language: "es",
    original_title: "Cosas imposibles",
    overview:
      "A widow who is tormented by the memory of her abusive husband befriends a young man.",
    popularity: 11.868,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069956/Poster/top6_xs68vb.jpg",
    release_date: "2021-06-17",
    title: "Impossible Things",
    video: false,
    vote_average: 8.6,
    vote_count: 255,
  },
  {
    adult: false,
    backdrop_path: "/3RMLbSEXOn1CzLoNT7xFeLfdxhq.jpg",
    genre_ids: (2)[(10749, 16)],
    id: 372754,
    original_language: "ja",
    original_title: "同級生",
    overview:
      "Rihito Sajo, an honor student with a perfect score on the entrance exam and Hikaru Kusakabe, in a band and popular among girls, would have never crossed paths. Until one day they started talking at the practice for their school's upcoming chorus festival. After school, the two meet regularly, as Hikaru helps Rihito to improve his singing skills. While they listen to each other's voice and harmonize, their hearts start to beat together.",
    popularity: 14.213,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069956/Poster/top7_m2kewk.jpg",
    release_date: "2016-02-20",
    title: "Dou kyu sei- Classmates",
    video: false,
    vote_average: 8.5,
    vote_count: 237,
  },
  {
    adult: false,
    backdrop_path: "/hZth9NCeXvvO7Xi98d8q34e1Ier.jpg",
    genre_ids: (3)[(16, 10751, 14)],
    id: 129,
    original_language: "ja",
    original_title: "千と千尋の神隠し",
    overview:
      "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
    popularity: 88.241,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069954/Poster/top8_cxl94i.jpg",
    release_date: "2001-07-20",
    title: "Spirited Away",
    video: false,
    vote_average: 8.5,
    vote_count: 13044,
  },
  {
    adult: false,
    backdrop_path: "/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg",
    genre_ids: (3)[(10749, 16, 18)],
    id: 372058,
    original_language: "ja",
    original_title: "君の名は。",
    overview:
      "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki's body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
    popularity: 158.416,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069957/Poster/top9_rr4nn7.jpg",
    release_date: "2016-08-26",
    title: "Your Name.",
    video: false,
    vote_average: 8.5,
    vote_count: 8866,
  },
];

const actionMovies = [
  {
    adult: false,
    backdrop_path: "/wcKFYIiVDvRURrzglV9kGu7fpfY.jpg",
    genre_ids: (3)[(14, 28, 12)],
    id: 453395,
    original_language: "en",
    original_title: "Doctor Strange in the Multiverse of Madness",
    overview:
      "Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.",
    popularity: 4480.794,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069961/Poster/trending3_wxnbcl.jpg",
    release_date: "2022-05-04",
    title: "Doctor Strange in the Multiverse of Madness",
    video: false,
    vote_average: 7.5,
    vote_count: 4368,
  },
  {
    adult: false,
    backdrop_path: "/p1F51Lvj3sMopG948F5HsBbl43C.jpg",
    genre_ids: (3)[(28, 12, 14)],
    id: 616037,
    original_language: "en",
    original_title: "Thor: Love and Thunder",
    overview:
      "After his retirement is interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods, Thor enlists the help of King Valkyrie, Korg, and ex-girlfriend Jane Foster, who now inexplicably wields Mjolnir as the Mighty Thor. Together they embark upon a harrowing cosmic adventure to uncover the mystery of the God Butcher's vengeance and stop him before it's too late.",
    popularity: 3675.753,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069961/Poster/trending2_tny8rl.jpg",
    release_date: "2022-07-06",
    title: "Thor: Love and Thunder",
    video: false,
    vote_average: 6.9,
    vote_count: 791,
  },
  {
    adult: false,
    backdrop_path: "/393mh1AJ0GYWVD7Hsq5KkFaTAoT.jpg",
    genre_ids: (3)[(12, 28, 878)],
    id: 507086,
    original_language: "en",
    original_title: "Jurassic World Dominion",
    overview:
      "Four years after Isla Nublar was destroyed, dinosaurs now live—and hunt—alongside humans all over the world. This fragile balance will reshape the future and determine, once and for all, whether human beings are to remain the apex predators on a planet they now share with history's most fearsome creatures.",
    popularity: 3190.202,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069963/Poster/trending1_zrea2f.jpg",
    release_date: "2022-06-01",
    title: "Jurassic World Dominion",
    video: false,
    vote_average: 6.6,
    vote_count: 1169,
  },
  {
    adult: false,
    backdrop_path: "/tqUD26YGjKmFqOJAgbNBah1gX0N.jpg",
    genre_ids: (5)[(16, 878, 12, 28, 10751)],
    id: 718789,
    original_language: "en",
    original_title: "Lightyear",
    overview:
      "Legendary Space Ranger Buzz Lightyear embarks on an intergalactic adventure alongside a group of ambitious recruits and his robot companion Sox.",
    popularity: 2710.323,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069954/Poster/action4_jsztx9.jpg",
    release_date: "2022-06-15",
    title: "Lightyear",
    video: false,
    vote_average: 7,
    vote_count: 460,
  },
  {
    adult: false,
    backdrop_path: "/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg",
    genre_ids: (2)[(28, 18)],
    id: 361743,
    original_language: "en",
    original_title: "Top Gun: Maverick",
    overview:
      "After more than thirty years of service as one of the Navy's top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.",
    popularity: 2613.435,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069958/Poster/action5_ngd76z.jpg",
    release_date: "2022-05-24",
    title: "Top Gun: Maverick",
    video: false,
    vote_average: 8.4,
    vote_count: 1548,
  },
  {
    adult: false,
    backdrop_path: "/zGLHX92Gk96O1DJvLil7ObJTbaL.jpg",
    genre_ids: (3)[(14, 12, 28)],
    id: 338953,
    original_language: "en",
    original_title: "Fantastic Beasts: The Secrets of Dumbledore",
    overview:
      "Professor Albus Dumbledore knows the powerful, dark wizard Gellert Grindelwald is moving to seize control of the wizarding world. Unable to stop him alone, he entrusts magizoologist Newt Scamander to lead an intrepid team of wizards and witches. They soon encounter an array of old and new beasts as they clash with Grindelwald's growing legion of followers.",
    popularity: 1695.732,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069955/Poster/action6_lm6ata.jpg",
    release_date: "2022-04-06",
    title: "Fantastic Beasts: The Secrets of Dumbledore",
    video: false,
    vote_average: 6.8,
    vote_count: 2226,
  },
  {
    adult: false,
    backdrop_path: "/egoyMDLqCxzjnSrWOz50uLlJWmD.jpg",
    genre_ids: (4)[(28, 12, 10751, 35)],
    id: 675353,
    original_language: "en",
    original_title: "Sonic the Hedgehog 2",
    overview:
      "After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.",
    popularity: 1784.175,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069953/Poster/action7_mymlbc.jpg",
    release_date: "2022-03-30",
    title: "Sonic the Hedgehog 2",
    video: false,
    vote_average: 7.7,
    vote_count: 2460,
  },
  {
    adult: false,
    backdrop_path: "/ocUp7DJBIc8VJgLEw1prcyK1dYv.jpg",
    genre_ids: (3)[(28, 12, 878)],
    id: 634649,
    original_language: "en",
    original_title: "Spider-Man: No Way Home",
    overview:
      "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    popularity: 1602.44,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069951/Poster/action8_euspaz.jpg",
    release_date: "2021-12-15",
    title: "Spider-Man: No Way Home",
    video: false,
    vote_average: 8.1,
    vote_count: 14090,
  },
  {
    adult: false,
    backdrop_path: "/5PnypKiSj2efSPqThNjTXz8jwOg.jpg",
    genre_ids: (2)[(14, 28)],
    id: 759175,
    original_language: "en",
    original_title: "The Princess",
    overview:
      "A beautiful, strong-willed young royal refuses to wed the cruel sociopath to whom she is betrothed and is kidnapped and locked in a remote tower of her father's castle. With her scorned, vindictive suitor intent on taking her father's throne, the princess must protect her family and save the kingdom.",
    popularity: 2126.827,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069952/Poster/action9_yqjall.jpg",
    release_date: "2022-06-16",
    title: "The Princess",
    video: false,
    vote_average: 6.5,
    vote_count: 107,
  },
];

const romanceMovies = [
  {
    adult: false,
    backdrop_path: "/t9hNIUFcy0tYu55IPxjxRTTdZ6X.jpg",
    genre_ids: (2)[(10749, 18)],
    id: 829557,
    original_language: "en",
    original_title: "365 Days: This Day",
    overview:
      "Laura and Massimo are back and hotter than ever. But the reunited couple's new beginning is complicated by Massimo's family ties and a mysterious man who enters Laura's life to win her heart and trust, at any cost.",
    popularity: 454.304,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069952/Poster/rom1_jiqhka.jpg",
    release_date: "2022-04-27",
    title: "365 Days: This Day",
    video: false,
    vote_average: 5.8,
    vote_count: 602,
  },
  {
    adult: false,
    backdrop_path: "/8vn4eis4xk6cnOnAuAcyzPbqVb0.jpg",
    genre_ids: (2)[(10749, 18)],
    id: 745376,
    original_language: "en",
    original_title: "Hello, Goodbye, and Everything in Between",
    overview:
      "Clare and Aidan, who after making a pact that they would break up before college, find themselves retracing the steps of their relationship on their last evening as a couple. The epic date leads them to familiar landmarks, unexpected places, and causes them to question whether high school love is meant to last.",
    popularity: 464.965,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069950/Poster/rom2_joxajl.jpg",
    release_date: "2022-07-06",
    title: "Hello, Goodbye, and Everything in Between",
    video: false,
    vote_average: 5.9,
    vote_count: 45,
  },
  {
    adult: false,
    backdrop_path: "/ba3oFhz6DkzSjVXsr50AGRMkfh8.jpg",
    genre_ids: (2)[(35, 10749)],
    id: 810171,
    original_language: "en",
    original_title: "The Valet",
    overview:
      "World famous movie star Olivia faces a PR disaster when a paparazzi snaps a photo of her with her married lover, Vincent. The hard-working valet Antonio accidentally appears in the same photo and is enlisted to pose as Olivia's new boyfriend as a cover-up. This ruse with Olivia thrusts Antonio into the spotlight and unexpected chaos.",
    popularity: 364.162,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069952/Poster/rom3_c9vn5g.jpg",
    release_date: "2022-05-11",
    title: "The Valet",
    video: false,
    vote_average: 7.8,
    vote_count: 269,
  },
  {
    adult: false,
    backdrop_path: "/dsGDdoWBiL7VzTAXoH6q3kh1VKW.jpg",
    genre_ids: (2)[(35, 10749)],
    id: 982939,
    original_language: "pl",
    original_title: "Parada serc",
    overview:
      "A careerist from Warsaw, who does not like dogs, has to go to Kraków for professional reasons, where she meets a charming widower, his son and their four-legged pet.",
    popularity: 305.889,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069949/Poster/rom4_e6srfk.jpg",
    release_date: "2022-06-15",
    title: "Heart Parade",
    video: false,
    vote_average: 5.6,
    vote_count: 29,
  },
  {
    adult: false,
    backdrop_path: "/4uwOKYaySkczmZ5C4EO50Ay3IoT.jpg",
    genre_ids: (2)[(35, 10749)],
    id: 846250,
    original_language: "en",
    original_title: "Fire Island",
    overview:
      "A group of queer best friends gather in the Fire Island Pines for their annual week of love and laughter, but when a sudden change of events jeopardizes their summer in gay paradise, their bonds as a chosen family are pushed to the limit.",
    popularity: 294.771,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069949/Poster/rom5_gtiabp.jpg",
    release_date: "2022-06-09",
    title: "Fire Island",
    video: false,
    vote_average: 7,
    vote_count: 66,
  },
  {
    adult: false,
    backdrop_path: "/lV3UFPPxDIPelh46G9oySXN9Mcz.jpg",
    genre_ids: (2)[(10749, 18)],
    id: 744275,
    original_language: "en",
    original_title: "After We Fell",
    overview:
      "Just as Tessa's life begins to become unglued, nothing is what she thought it would be. Not her friends nor her family. The only person that she should be able to rely on is Hardin, who is furious when he discovers the massive secret that she's been keeping. Before Tessa makes the biggest decision of her life, everything changes because of revelations about her family.",
    popularity: 304.025,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069951/Poster/rom6_h0sp3t.jpg",
    release_date: "2021-09-01",
    title: "After We Fell",
    video: false,
    vote_average: 7.2,
    vote_count: 1768,
  },
  {
    adult: false,
    backdrop_path: "/pCp9kiUEqDBJQiC9o5p2jrfSJbJ.jpg",
    genre_ids: (3)[(35, 10751, 10749)],
    id: 937337,
    original_language: "es",
    original_title: "¡Qué despadre!",
    overview:
      "Pedro is a single man in his forties who likes to party, has no children and lives at night. Everything changes when he meets Alin. She mentions to him that she is looking for her dad and that there is a high probability that it is him.",
    popularity: 256.2,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069949/Poster/rom7_xea4fs.jpg",
    release_date: "2022-02-09",
    title: "What a Father!",
    video: false,
    vote_average: 8.3,
    vote_count: 98,
  },
  {
    adult: false,
    backdrop_path: "/sS4MadD7pKMt251vKxdJo2YrkYP.jpg",
    genre_ids: (2)[(10749, 18)],
    id: 744276,
    original_language: "en",
    original_title: "After Ever Happy",
    overview:
      "As a shocking truth about a couple's families emerges, the two lovers discover they are not so different from each other. Tessa is no longer the sweet, simple, good girl she was when she met Hardin — any more than he is the cruel, moody boy she fell so hard for.",
    popularity: 260.546,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069958/Poster/rom8_dppdnk.jpg",
    release_date: "2022-08-25",
    title: "After Ever Happy",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/rGhCGxE2WWqzyRa8dy448uYGr4w.jpg",
    genre_ids: (2)[(35, 10749)],
    id: 908762,
    original_language: "en",
    original_title: "My Fake Boyfriend",
    overview:
      "A young man in a tricky situation follows the advice of his unconventional best friend and uses social media to create a fake boyfriend to keep his awful ex-lover out of his life. But everything backfires when he meets the real love of his life, and breaking up with his fake boyfriend proves hard to do.",
    popularity: 262.194,
    poster_path:
      "https://res.cloudinary.com/utdyht/image/upload/v1658069951/Poster/rom9_x7gz1h.jpg",
    release_date: "2022-06-10",
    title: "My Fake Boyfriend",
    video: false,
    vote_average: 6.6,
    vote_count: 50,
  },
];

export { trending, originals, topRated, actionMovies, romanceMovies };
